run_id: prototype-1

text_features: ['name_1', 'name_2', 'categories_1', 'categories_2']

stopwords:
  languages: ['arabic', 'azerbaijani', 'bengali', 'catalan', 'chinese',
              'croatian', 'danish', 'dutch', 'english', 'finnish', 'french',
              'german', 'greek', 'hebrew', 'hindi', 'hungarian', 'indonesian',
              'irish', 'italian', 'japanese', 'kazakh', 'nepali', 'norwegian',
              'persian', 'polish', 'portuguese', 'romanian', 'russian', 'sinhala',
              'spanish', 'swedish', 'tagalog', 'tamil', 'tatar', 'telugu', 'thai',
              'turkish', 'ukrainian', 'urdu', 'vietnamese']

  additional_stopwords: []

columns_to_remove_emojis: ['name_1', 'name_2', 'categories_1', 'categories_2']




  
