run_id: ${run_id}

stopwords:
  columns: ['name_1', 'name_2', 'categories_1', 'categories_2']
  languages: ['arabic', 'azerbaijani', 'bengali', 'catalan', 'chinese',
              'croatian', 'danish', 'dutch', 'english', 'finnish', 'french',
              'german', 'greek', 'hebrew', 'hindi', 'hungarian', 'indonesian',
              'irish', 'italian', 'japanese', 'kazakh', 'nepali', 'norwegian',
              'persian', 'polish', 'portuguese', 'romanian', 'russian', 'sinhala',
              'spanish', 'swedish', 'tagalog', 'tamil', 'tatar', 'telugu', 'thai',
              'turkish', 'ukrainian', 'urdu', 'vietnamese']